package eu.europa.ec.sante.openncp.core.client.connector.cdadisplaytool;

import eu.europa.ec.sante.openncp.core.client.connector.cdadisplaytool.exceptions.TerminologyFileNotFoundException;
import eu.europa.ec.sante.openncp.core.client.connector.cdadisplaytool.exceptions.UITransformationException;
import org.junit.Ignore;
import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.nio.file.attribute.BasicFileAttributes;

@Ignore("Test to revise - Exclude unit test from test execution")
public class DisplayTest {

    private static final Logger LOGGER = LoggerFactory.getLogger(DisplayTest.class);

    //	@Test
    private void fileTest(final String input, final TRANSFORMATION type) throws UITransformationException, IOException {

        LOGGER.info("Transforming file: " + input);

        String cda = "";
        try {
            cda = CdaXSLTransformer.getInstance().readFile(input);
        } catch (final Exception e) {
            LOGGER.error("File not found");
        }
        String out = "";
        switch (type) {
            case ForPDF:
                out = CdaXSLTransformer.getInstance().transformForPDF(cda, "fr-BE", false);
                break;
            case UsingStandardCDAXsl:
                out = CdaXSLTransformer.getInstance().transformUsingStandardCDAXsl(cda);
            case WithOutputAndDefinedPath:
                out = CdaXSLTransformer.getInstance().transformWithOutputAndDefinedPath(cda, "fr-BE", "",
                        Paths.get(System.getenv("EPSOS_PROPS_PATH"), "EpsosRepository"));
            case WithOutputAndUserHomePath:
                out = CdaXSLTransformer.getInstance().transformWithOutputAndUserHomePath(cda, "fr-BE", "");

        }
        final String filename = Paths.get(input).getFileName().toString();
        final String stripExt = filename.substring(0, filename.lastIndexOf("."));
        final String pt = Paths.get(System.getenv("EPSOS_PROPS_PATH"), "EpsosRepository", "out", stripExt + ".html").toString();
        try (final Writer writer = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(pt), StandardCharsets.UTF_8))) {
            writer.write(out);
        }
    }

    //	@Test
    private void folderTest(final String input, final TRANSFORMATION type) {
        final Path path = Paths.get(input);
        try {
            Files.walkFileTree(path, new SimpleFileVisitor<Path>() {
                @Override
                public FileVisitResult visitFile(final Path file, final BasicFileAttributes attrs) throws IOException {
                    if (!attrs.isDirectory()) {
                        try {
                            fileTest(file.toString(), type);
                        } catch (final UITransformationException e) {
                            LOGGER.error("{}: '{}'", e.getClass(), e.getMessage(), e);
                        }
                    }
                    return FileVisitResult.CONTINUE;
                }
            });
        } catch (final Exception e) {
            LOGGER.error("{}: '{}'", e.getClass(), e.getMessage(), e);
        }
    }

    /**
     * <p>This test is quite brittle and as such should not be used as a normal test/integration test flow.
     * The goal of this test is to test the cda display tool functionality by transforming a clinical CDA document in xml format to
     * an html file using a xslt transformation.</p>
     *
     * <p>To properly run it you need the following preconditions:
     * <ol>
     *     <li>an environment variable 'EPSOS_PROPS_PATH' that points to a valid folder on your machine</li>
     *     <li>Inside that 'EPSOS_PROPS_PATH' folder you need to create a folder called 'EpsosRepository'</li>
     *     <li>Inside this 'EpsosRepository' folder you need have a folder called 'out'</li>
     *     <li>And finally inside the 'EpsosRepository' folder you need have the xml files that are generated by the combination of TSAM-sync and TSAM-exporter</li>
     *     <li>/li>
     * </ol>
     * The folder structure (with 'local_epsos_props_path' as 'EPSOS_PROPS_PATH') should look like:
     * <pre>
     *   local_epsos_props_path
     *   └── EpsosRepository
     *       ├── out
     *       ├── 1.3.6.1.4.1.12559.11.10.1.3.1.42.1.xml
     *       ├── 1.3.6.1.4.1.12559.11.10.1.3.1.42.2.xml
     *       └── ... (additional ValueSet XML files)
     * </pre>
     * </p>
     * <p>
     *     The result of this test should be an html file that represents the given clinical CDA document in a human-readable format.
     *     This .html file should be found in the 'out' folder inside the 'EpsosRepository' that resides in your 'EPSOS_PROPS_PATH' folder.
     * </p>
     *
     * @throws UITransformationException
     * @throws IOException
     */
    @Test
    public void runFile() throws UITransformationException, IOException {
        // Replace this with your own CDA document you want to transform.
        // You can find one as an example in the 'openncp-core/openncp-core-server-mock/src/main/resources/psstore' folder (2-1234-W8.xml for example)
        fileTest("/Users/mathiasghys/Downloads/1-1234-W8.xml", TRANSFORMATION.WithOutputAndDefinedPath);
    }

    @Test
    public void readFile() throws TerminologyFileNotFoundException, IOException, UITransformationException {

        final String out = CdaXSLTransformer.getInstance().readFile("samples/1-5678.xml");
        final String pt = Paths.get(System.getenv("EPSOS_PROPS_PATH"), "EpsosRepository", "out", "readfile.txt").toString();
        try (final Writer writer = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(pt), StandardCharsets.UTF_8))) {
            writer.write(out);
        }
    }

    private enum TRANSFORMATION {
        WithOutputAndUserHomePath, ForPDF, UsingStandardCDAXsl, WithOutputAndDefinedPath
    }
}
